module.exports = {
  // ... existing constants
  SALE_STATUS: {
    PENDING: 'PENDING',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED'
  },
  HCS_MESSAGE_TYPES: {
    PROPERTY_TOKENIZED: 'PROPERTY_TOKENIZED',
    TOKEN_SALE: 'TOKEN_SALE',
    DISTRIBUTION: 'DISTRIBUTION'
  },
  MIN_PURCHASE_QUANTITY: 1,
  MAX_PURCHASE_QUANTITY: 10000
};